config/routes.rb
RailsBlog::Application.routes.draw do

  root 'posts#index'
  
  resources :sessions
  resources :users, :only => [:new, :show, :index]
  resources :tags, :only => [:show, :index]
  
  resources :posts do 
    resources :comments, :only => [:new, :create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :post_tags
  has_many :tags, :through => :post_tags
  accepts_nested_attributes_for :tags, reject_if: lambda {|attributes| attributes['name'].blank?}
  validates_presence_of :name, :content
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, :through => :post_tags

  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :user_id, :tag_ids => [], :tags_attributes => [:id, :name], :comments_attributes => [:content, :user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
  end


  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :user_id, :value => session["user_id"] %>
    Tags:
  </div>

  <div class="field">
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
    <%= f.fields_for(:tags, Tag.new) do |tag_form| %>
      <p>Add a new tag:</p><br>
      <%= tag_form.label :name %>
      <%= tag_form.text_field :name %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<h2><%= link_to post.name, post %></h2> <span>written by: <%= post.user.name %> </span>

<% if current_user %>
  <p><%= link_to 'Edit', edit_post_path(post) %></p>
  <p><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% else %>
  <p> <%= link_to "Log in to edit or delete your Post", login_path %> </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<%= render @posts  %>


<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Title:</h3>
<%= @post.name %>
<h3>Content:</h3>
<%= @post.content %>
<h3>Posted by:</h3>
<%= @post.user.name %>
<h3>Tags:</h3>
<ul>
  <% @post.tags.each do |tag| %>
  <li><%= tag.name %></li>
  <% end %>
</ul>
<h3>Comments:</h3>
  <% @post.comments.each do |comment| %>
    <p><strong><%= comment.user.name %></strong> says ...</p> 
    <p><%= comment.content %> </p>
  <% end %>

<% if current_user %>
  <h4>Post a new comment:</h4>
  <%= form_for [@post, Comment.new] do |f| %>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %><br>
      <%= f.hidden_field :post_id, :value => @post.id %>
      <%= f.hidden_field :user_id, :value => session["user_id"] %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <%= link_to "Log In to Comment!", login_path %>
<% end %>

<% if current_user %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>
  <ul>
    <% @tags.each do |tag| %>
        <li> <%= link_to tag.name, tag %> </li>
    <% end %>
  </ul>
<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p> <%= @tag.name %> </p>
<ul>
    <% @tag.posts.each do |post| %>
      <li> <%= link_to post.name, post_path(post) %> </li>
    <% end %>
</ul>

<%= link_to 'Back', tags_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

    <% @users.each do |user| %>
        <h2> <%= link_to user.name, user %> </h2>
    <% end %>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @user.name %>  </h2>
<% @user.posts.each do |post| %>
  <p><%= post.name %></p>
  <p><%= post.content %></p>
  <% post.comments.each do |comment| %>
    <p><%= comment.content %>, by: <span> <%= comment.user.name %> </span></p>
  <% end %>
<% end %>


<%= link_to 'Back', users_path %>